#


from PyQt5 import QtCore, QtGui, QtWidgets,QtDBus
from PyQt5.QtWidgets import QTextEdit


class Ui_TextEditor(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(692, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 671, 601))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuStyle = QtWidgets.QMenu(self.menubar)
        self.menuStyle.setObjectName("menuStyle")
        self.menuTimeand_Date = QtWidgets.QMenu(self.menubar)
        self.menuTimeand_Date.setObjectName("menuTimeand_Date")
        self.menuText_Highliter = QtWidgets.QMenu(self.menubar)
        self.menuText_Highliter.setObjectName("menuText_Highliter")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp_2 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/Printe1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon3)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrint_Preview = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/search-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint_Preview.setIcon(icon4)
        self.actionPrint_Preview.setObjectName("actionPrint_Preview")
        self.actionExport_Pdf = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/exportpdf.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_Pdf.setIcon(icon5)
        self.actionExport_Pdf.setObjectName("actionExport_Pdf")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("1mages/ Drawer Closed.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon7)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon8)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon9)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon10)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/redo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon11)
        self.actionRedo.setObjectName("actionRedo")
        self.actionFont = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFont.setIcon(icon12)
        self.actionFont.setObjectName("actionFont")
        self.actionColor = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/colourr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon13)
        self.actionColor.setObjectName("actionColor")
        self.actionBold = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("images/bold.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon14)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("images/italic.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon15)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUndreline = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("images/edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndreline.setIcon(icon16)
        self.actionUndreline.setObjectName("actionUndreline")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("images/left.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeft.setIcon(icon17)
        self.actionLeft.setObjectName("actionLeft")
        self.actionCenter = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("images/center.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter.setIcon(icon18)
        self.actionCenter.setObjectName("actionCenter")
        self.actionRight = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("images/right.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRight.setIcon(icon19)
        self.actionRight.setObjectName("actionRight")
        self.actionJustify = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("images/justify.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJustify.setIcon(icon20)
        self.actionJustify.setObjectName("actionJustify")
        #self.actionRemove.QWtidgets.QAction(MainWindow)
        #icon22=QtGui.QIcon()
        #icon22.addPixmap(QtGui.QPixmap(""),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        #self.actionRemove.setIcon(icon22)
        #self.actionRemove.setObjectName("actionRemove")
        self.actionTime = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("images/time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTime.setIcon(icon21)
        self.actionTime.setObjectName("actionTime")
        self.actionDate = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("images/calendar-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDate.setIcon(icon22)
        self.actionDate.setObjectName("actionDate")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("images/sound-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon23)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHighlit = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("images/highlite.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHighlit.setIcon(icon24)
        self.actionHighlit.setObjectName("actionHighlit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("images/Itweek-Knob-Toolbar-Knob-Add - Copy - Copy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon25)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("images/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_2.setIcon(icon26)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.actionExport_Pdf)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)

        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuFormat.addAction(self.actionFont)
        self.menuFormat.addAction(self.actionColor)
        self.menuStyle.addAction(self.actionBold)
        self.menuStyle.addAction(self.actionItalic)
        self.menuStyle.addAction(self.actionUndreline)
        self.menuStyle.addSeparator()
        self.menuStyle.addAction(self.actionLeft)
        self.menuStyle.addAction(self.actionCenter)
        self.menuStyle.addAction(self.actionRight)
        self.menuStyle.addAction(self.actionJustify)
        #self.menuStyle.addAction(self.actionRemove)
        self.menuTimeand_Date.addAction(self.actionTime)
        self.menuTimeand_Date.addAction(self.actionDate)
        self.menuText_Highliter.addAction(self.actionHighlit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp_2.addAction(self.actionAbout_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuStyle.menuAction())
        self.menubar.addAction(self.menuTimeand_Date.menuAction())
        self.menubar.addAction(self.menuText_Highliter.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionColor)
        self.toolBar.addAction(self.actionFont)
        self.toolBar.addAction(self.actionBold)
        self.toolBar.addAction(self.actionItalic)
        self.toolBar.addAction(self.actionPrint_Preview)
        self.toolBar.addAction(self.actionAbout)
        #self.toolBar.addAction(self.actionRemove)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFormat.setTitle(_translate("MainWindow", "Format"))
        self.menuStyle.setTitle(_translate("MainWindow", "Style"))
        self.menuTimeand_Date.setTitle(_translate("MainWindow", "Time"))
        self.menuText_Highliter.setTitle(_translate("MainWindow", "Text Highliter"))
        self.menuHelp.setTitle(_translate("MainWindow", "Speaking"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar "))
        self.actionOpen.setText(_translate("MainWindow", "Open                   Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save                   Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionPrint.setText(_translate("MainWindow", "Print                  Ctrl+P"))
        self.actionPrint_Preview.setText(_translate("MainWindow", "Print Preview Ctrl+Shift+P "))
        self.actionExport_Pdf.setText(_translate("MainWindow", "Export Pdf        Ctrl+E"))
        self.actionExit.setText(_translate("MainWindow", "Exit                    Ctrl+Q"))
        self.actionCopy.setText(_translate("MainWindow", "Copy                    Ctrl+C"))
        self.actionCut.setText(_translate("MainWindow", "Cut                      Ctrl+X"))
        self.actionPaste.setText(_translate("MainWindow", "Paste                  Ctrl+V"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionFont.setText(_translate("MainWindow", "Font                   Ctrl+F"))
        self.actionColor.setText(_translate("MainWindow", "Color                 Ctrl+T"))
        self.actionBold.setText(_translate("MainWindow", "Bold                   Ctrl+B"))
        self.actionItalic.setText(_translate("MainWindow", "Italic               Ctrl+I"))
        self.actionUndreline.setText(_translate("MainWindow", "Undreline     Ctrl+shift+U"))
        self.actionLeft.setText(_translate("MainWindow", "Left                   Ctrl+L"))
        self.actionCenter.setText(_translate("MainWindow", "Center           Ctrl+shift+C"))
        self.actionRight.setText(_translate("MainWindow", "Right                 Ctrl+R"))
        self.actionJustify.setText(_translate("MainWindow", "Justify             Ctrl+J"))
        self.actionTime.setText(_translate("MainWindow", "Time               Ctrl+shift+T"))
        self.actionDate.setText(_translate("MainWindow", "Date                   Ctrl+D"))
        self.actionAbout.setText(_translate("MainWindow", "Speak             Ctrl+shift+S"))
        self.actionHighlit.setText(_translate("MainWindow", "Highlit             Ctrl+H"))
        self.actionNew.setText(_translate("MainWindow", "New                     Ctrl+N"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
        #self.actionRemove.setText(_translate("MainWindow","Remove"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_TextEditor()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
